export const MAX_COMMUNITY_REPORT_REQUEST_BYTES = 64 * 1024;
export const MAX_COMMUNITY_RECEIPT_RESPONSE_BYTES = 32 * 1024;
export const MAX_COMMUNITY_FEED_RESPONSE_BYTES = 4 * 1024 * 1024;
export const MAX_COMMUNITY_FEED_ENTRIES = 20_000;
export const MAX_COMMUNITY_FEED_ENTRY_VALUE_CHARS = 2_048;
export const MAX_COMMUNITY_FEED_RULE_ID_CHARS = 128;
export const MAX_COMMUNITY_IDENTITY_ALIASES = 32;
export const MAX_COMMUNITY_IDENTITY_DOMAINS = 32;
export const MAX_COMMUNITY_IDENTITY_TEXT_CHARS = 256;
export const MAX_COMMUNITY_DOMAIN_CHARS = 253;

// The portable recovery contract is also the production persistence ceiling:
// runtime storage must not successfully grow into a state the built-in backup
// tooling is guaranteed to reject.
export const MAX_COMMUNITY_AUTHORITATIVE_SOURCE_BYTES = 192 * 1024 * 1024;
export const MAX_COMMUNITY_SIGNING_KEY_FILE_BYTES = 64 * 1024;
export const COMMUNITY_STORAGE_KEY_BYTES = 32;
export const MAX_COMMUNITY_REPORT_JOURNAL_BYTES = 16 * 1024 * 1024;
export const MAX_COMMUNITY_AGGREGATE_DATABASE_BYTES =
  MAX_COMMUNITY_AUTHORITATIVE_SOURCE_BYTES -
  MAX_COMMUNITY_REPORT_JOURNAL_BYTES -
  (2 * MAX_COMMUNITY_SIGNING_KEY_FILE_BYTES) -
  COMMUNITY_STORAGE_KEY_BYTES;
